### ISSUE TITLE
Card number input field pattern

### ISSUE THREAD

**Issue by Veilleuse-00** [mollie/components-examples#26]
Hi!
Card number input field allows 16 digits + space + 3 digits.
Is it possible to limit it to 16 digits?
Thank you in advance.

**Comment by Marinolinderhof** [comment]
Hi, @Faign Thanks for your suggestion. 

While the majority of cards are indeed 16 digits it's not a given that the card number is 16 digits or even that the mask layout is 4-4-4-4. For example American Express is 4-6-5 and thus 15. You can try American Express in the demo you will see a different mask pattern. 

For reference (visa look for including vpay)
https://en.wikipedia.org/wiki/Payment_card_number

cheers Marino
