### ISSUE TITLE
Styles for placeholder doesn’t work

### ISSUE THREAD

**Issue by amin212121** [mollie/components-examples#28]
I try to to add this example but placeholder doesn’t change styles. Any idea?
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/36712833/199526059-b45a72cd-3987-4bf1-b429-579f2eb71497.png">

**Comment by ryanurban** [comment]
I'm also seeing this. The placeholder styles passed are not respected. (bump)

**Comment by doskarj** [comment]
Hey, thanks for reporting this issue!
We just released a new version with a fix for this.

Please let us know if you are still experiencing the issue, in the meantime closing this ticket.
