### ISSUE TITLE
Inputting an incomplete expiry date leads to JS console errors

### ISSUE THREAD

**Issue by andreychirikba** [mollie/components-examples#9]
![17 Nov 2020 at 14_06_32](https://user-images.githubusercontent.com/30152071/99393828-34e1dc00-28de-11eb-8860-9f26f5628bd0.gif)
`Uncaught TypeError: Cannot read property 'trim' of undefined
    at e.setCorrectedPasteValue (components.e009e891.js:15)
    at e.onChange (components.e009e891.js:15)
    at HTMLInputElement.<anonymous> (components.e009e891.js:1)`

PS. Is this the right place for Components issues?

**Comment by pabloroman** [comment]
Thank you for reporting this @andreychirikba, we have taken note of this issue and we'll address it in a future release.

**Comment by Veilleuse-00** [comment]
Would be good to see this new release (2022) 😆.

**Comment by sebastiansommer** [comment]
+1

**Comment by Rbtsv2** [comment]
"Uncaught TypeError: r[1] is undefined" https://js.mollie.com/v1/components.5d2ae488.js:15  :/ 
error triggered when entering the expiry date, perhaps the trim function which generates this error.

**Comment by Veilleuse-00** [comment]
Yes, it seems the trim() function is applied on an "undefined" string.

**Comment by Rbtsv2** [comment]
the event is triggered at the second character entered in the field but as the last 2 are not entered it generates an error because the table is empty, perhaps the event should be triggered when the user completes the entire field expire date ?

**Comment by doskarj** [comment]
Hey 👋 , thanks for the issue report.
It has been resolved, you should not encounter this issue anymore.

Closing the ticket.
